version: "3"

services:
  database:
    image: mongo
    restart: always
    environment:
      NEXT_PUBLIC_GOOGLE_ANALYTICS: "G-V9B9Z5S7D6"
    REACT_APP_SERVICE_ID: "service_vuygmmf"
    REACT_APP_TEMPLATE_ID: "template_n3imorc"
    REACT_APP_USER_ID: "630uiCBV0K235A4GY"
    DATABASE_CONNECTION: "mongodb+srv://chrisdietrich366:Devindiet1@dietrichlandcare.kq6v5mn.mongodb.net/test"
    STRIPE_SECRET_KEY: "sk_test_51MzLPJLlDdCMZNGTipCL0kWMP2hpQ6oRMPvsrcDe9bS2MkjcgkeOzHKTHPRrFPslhIaWOTvV96O1xWbXTkD012sQ00m9g5ldBK"
    SALT_KEY: "_2b_10_P5AIfxtepuxG/VD6plnRve"
    NEXT_PUBLIC_BASE_URL: "http://localhost:3000/"
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "pk_test_51MzLPJLlDdCMZNGTXhjuLErlIWeyQs3LIkEcKbyvA5FR4dRjbkQx2d0MTDPN76jtqtQdPp4kzu0TJK1auXt57bOl00ViaITvBt0"

    frontend:
    build:
      context: .
    ports:
      - "3000:3000"
